### ISSUE TITLE
Alternative to OAuth Authentication flow

### ISSUE THREAD

**Issue by shawnthroop** [pnut-api/api-spec#1]
In order to provide a better and more native user experience on mobile apps there should be authentication flow that can avoid the OAuth web view tango.

In the App.net API, this was called [Password Flow](https://developers.app.net/reference/authentication/flows/password/).

**Comment by 33mhz** [comment]
I do plan to add this. Will be looking at how best to do it. Among other things, per-client passwords are being considered.

**Comment by 33mhz** [comment]
[Password flow](https://pnut.io/docs/authentication/password-flow) is complete! Let me know if you have issues. I will try to flesh out instructions (and policy/restrictions) as usual.

**Comment by shawnthroop** [comment]
@33mhz this is fantastic, thank you.
