### ISSUE TITLE
expand verification options

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/api-spec#15]
sevan asked to be able to verify more than one domain. I'm open to other verifications, as well. Something to think about.

**Comment by 33mhz** [comment]
I don't want to have an unending list of verified things returned on a user object. Possibly only return an expanded list on the user when the user is looked up (`/users/{user_id}`), or add an endpoint for verified identities, and expand the identity verification into an unending list and possibly even a whole section unto itself.

**Comment by shawnthroop** [comment]
@33mhz I always thought of a verified domain as a way of signaling that you are a real person. I don't see how more than one domain would improve that. IMO showcasing multiple domains should be done in the description field.

**Comment by 33mhz** [comment]
It could simply be a core user `raw` item, too. I don't particularly want to duplicate something like keybase.io, but it also may be very little work to allow other ways of verifying one's self. I'm not sure if I care more that a person be able to verify a URL vs something else. Thanks for the input!

**Comment by shawnthroop** [comment]
I'm not familiar with keybase.io but other verification methods could be cool. Right now I assume your users are generally people with domains (i.e. geeks haha) but in the future more methods could be useful. I tried to get verified on Twitter… ugh. Good thinking (and thanks for having this place to give input 😉)

**Comment by brainseller** [comment]
At first I thought of it as a way to verify (and show) your domains, but it really is just a way to verify your pnut account. Therefore one domain is enough. But multiple verifications (domains and maybe other accounts) wouldn't be of harm. 

Assuming multiple verifications, still pnut is not keybase, so it needs not to be returned for every user lookup what verifications are in place. Just if it's verified. A list of verifications could then be returned from an extra endpoint.

**Comment by 33mhz** [comment]
@brainseller Thanks, agreed. I like the idea, and have it in my future features, but will turn to it on a rainy day, when I want a break from More Important Features. :)

**Comment by 33mhz** [comment]
Still doesn't seem necessary, so I will bench this for now, and revisit if/when it might be useful.
