### ISSUE TITLE
Allow underscores in tags

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/api-spec#24]
Should I? I didn't realize Twitter allows them. ADN doesn't. It's not important to me, but the Germans have been adding them--I assume out of familiarity with Twitter. 🤷‍

*Correction: ADN does! It's a deal.

**Comment by blumenkraft** [comment]
"familiarity with Twitter"... you got to be kidding me! :P

**Comment by 33mhz** [comment]
Implemented.
