### ISSUE TITLE
More Core Raw Types

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/api-spec#25]
`io.pnut.core.crosspost`

What else?

**Comment by blumenkraft** [comment]
Location data?

**Comment by 33mhz** [comment]
@blumenkraft ADN's implementation involved a whole different API for tracking locations: https://github.com/appdotnet/object-metadata/blob/master/annotations/net.app.core.checkin.md https://github.com/appdotnet/object-metadata/blob/master/annotations/net.app.ohai.location.md. That kind of implementation is on my long-term features list, but it's near the end of the list.

**Comment by 33mhz** [comment]
`io.pnut.core.channel.invite`

`io.pnut.core.channel.metadata`

`io.pnut.core.geolocation`?

**Comment by 33mhz** [comment]
Added channel invite, crosspost, oembed metadata. Will consider others in the future.
