### ISSUE TITLE
Description for Clients

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/api-spec#3]
Since I have endpoints for retrieving additional data on clients by their ID, it seems like it could be helpful to allow developers to detail a "description" for their client.

**Comment by shawnthroop** [comment]
It might be helpful to include a URL along side the description. It would standardise linking back to clients and encourage developers from putting potentially long user-visible URLs into the description.

**Comment by 33mhz** [comment]
Right now the client endpoint returns "created_at", "created_by", "id", "link", "name", and "posts" (post count). Description would round it out pretty well.

**Comment by shawnthroop** [comment]
@33mhz that sounds great

**Comment by 33mhz** [comment]
Added. Basic editing only from your pnut.io developer area. Only retrieved when you call the client details from the API.
