### ISSUE TITLE
 /users/{user_id}/clients endpoint seems not to work

### ISSUE THREAD

**Issue by kaiwood** [pnut-api/api-spec#35]
Just checked this endpoint while looking for missing endpoints in [pnut-butter](https://github.com/kaiwood/pnut-butter) and it looks like this one does not work as intended. `/users/@33MHz/clients` from the doc example shows a couple of clients, but `/users/@kwood/clients` does not. (checked with user ids instead of usernames and with other developers that have their client listed in the app directory).

Hardcoded? :P

**Comment by 33mhz** [comment]
Confirmed. I moved some of how that data is stored, and forgot to update this endpoint. Will be fixed on the next patch.

**Comment by 33mhz** [comment]
*No, hotfixed it now. Good to go.

**Comment by kaiwood** [comment]
Just tested, works now as expected 👍
