### ISSUE TITLE
Password validation issues

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#44]
On this page: https://pnut.io/join a new user can create an account. There's a password field, and underneath it states: "Password must be 7 to 128 characters."

1) The length doesn't seem to be checked. As long as there's 1 character in the field, the user can proceed to the next step of the account creation (payment in the example here)

![screen shot 2017-12-02 at 9 39 08 pm](https://user-images.githubusercontent.com/1012467/33521796-17d5a9b2-d7aa-11e7-9e8f-183a7ef8fe6c.png)

2) No other constraints are required for the password when creating an account. In my case, I created a long password (8 words separated by dots). However, after the account is successfully made, you can go to this page: https://pnut.io/account/security to change your password. Here it also states "Passwords must be 7-128 characters.", but when trying to change the password, there are additional constraints that must be met. "Passwords must include lowercase and a number". This validation is applied to the current password as well, making it impossible* for a user to change their password if it didn't already coincidentally meet those requirements.

![screen shot 2017-12-02 at 9 51 02 pm](https://user-images.githubusercontent.com/1012467/33521823-f21c65ca-d7aa-11e7-9c5a-987957f9403f.png)

*impossible, unless you edit the source of the web site and remove the validation, at which point the server does actually change the password. Removing the client side validation also allows you to again pick a new password that doesn't meet the set requirements. I.e.:, the client is enforcing rules not required by the server.

The password change form should not validate the current password (other than standard input validation, checking for SQL Injection etc). The server side check to see if the password is correct should suffice and allow anyone to change their password regardless of what the password criteria was when the password was created. Next, the client side validation fo the new password should match the server side validation.

3) While not really a bug, I'd suggest changing the password requirements to be 12-128 characters, and drop the lowercase and number requirement. That makes the minimum password more secure, and works with more password manager password generation systems.

**Comment by DaveWoodCom** [comment]
Note, when signing up using an invite code, without the Stripe payment option, the password field is validated client side. The alert however doesn't match the requirements it's actually looking for. It states the length, but omits that it requires a lowercase character & number.

![screen shot 2017-12-02 at 11 24 36 pm](https://user-images.githubusercontent.com/1012467/33522358-988ae1c2-d7b8-11e7-8d08-73e73ed871d3.png)

**Comment by 33mhz** [comment]
A while ago I removed server-side password requirements, but apparently didn't consistently remove it!
