### ISSUE TITLE
Unable to show Pnut Badge on Profile

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#45]
On this page: https://pnut.io/account/support there's an option to "Show badge on our profile".

Using a newly generated, paid account, when enabling the checkbox to show the badge and hitting save, the error "You have no badge to show." is displayed.

![screen shot 2017-12-02 at 10 05 19 pm](https://user-images.githubusercontent.com/1012467/33521904-5da69836-d7ad-11e7-8678-6398ce166d54.png)

User should be able to turn that badge on.

**Comment by 33mhz** [comment]
Fixed.
