### ISSUE TITLE
Profile form is confusing and causes data loss

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#46]
This page: https://pnut.io/account#profile allows a user to edit their avatar, cover photo, name and description.

![screen shot 2017-12-02 at 10 11 38 pm](https://user-images.githubusercontent.com/1012467/33521927-ecf64b26-d7ad-11e7-89c1-b589a752c640.png)

It appears to be one form. A user is likely to enter their name, type in a description (possibly a few paragraphs), select an image file from their computer to use as their avatar, hit upload, and boom. They've just lost everything they'd typed into the description field. Granted it's not a lot of information, but it still could have been 10-15 minutes of work as someone meticulously attempts to introduce themselves to this new community. And then it's all lost because the form didn't tell the user it was about to be cleared when the file was uploaded, or the form didn't just keep that information available when the page reloaded. Ideally this would be just one form, remove the separate "Upload" buttons, and just have the files uploaded when "Update" is pressed. (Even better if the photo just automatically uploaded in the background as it was selected).

**Comment by 33mhz** [comment]
Long-term this will disappear completely, but I'll clarify the form handling.
