### ISSUE TITLE
RSS feeds don't work (right away)

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#47]
When setting up my new account yesterday, I went to this page: https://pnut.io/account/rss and enabled RSS.

The page gave me two URL's one for a personal stream, one for a unified stream. I copied them and added them to my RSS reader. The RSS reader complained that the links were invalid.

Checking the links via curl on the command line, the server was returning HTTP Error code 500 for both URLs.

When I check the URLs now, they are working as expected. So either there was an issue yesterday that's been corrected (if so, close this ticket and ignore), or the streams take some time before they're actually set up and working. If that's the case, there should be a note on the page to indicate that.

**Comment by 33mhz** [comment]
Yes, it was an issue briefly. Fixed as observed.
