### ISSUE TITLE
Third Party App login issues

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#48]
These issues have been tested using Apero on macOS, but appear to be related to all third party clients using the web login form.

1. When attempting to log in, the user is presented with this screen:

![screen shot 2017-12-02 at 10 30 37 pm](https://user-images.githubusercontent.com/1012467/33522031-7879b5d2-d7b0-11e7-8a60-e42548eb6829.png)

If the user enters an incorrect username/password pair, an error message is displayed:

![screen shot 2017-12-02 at 10 31 43 pm](https://user-images.githubusercontent.com/1012467/33522038-9c1172e6-d7b0-11e7-892e-66a88d7cabdc.png)

Note that in the first screen, there's no links for "Apps", "Updates", "Docs", or "Login" at the top, and no links in the footer at the bottom. The incorrect login has taken the user to the normal web login page, rather than back to the third party specific login page. Even if the user correctly enters their info now, the third party app will never been sent the credentials needed. The pnut.io web page just loads in the window instead.

2. If MFA is enabled on your account, it's impossible to log into a third party app. The username/password is accepted, and then this screen is displayed (as expected):

![screen shot 2017-12-02 at 11 03 11 pm](https://user-images.githubusercontent.com/1012467/33522221-0aaf1fe2-d7b5-11e7-966d-9bfa23e13b57.png)

However, after entering the MFA code, the screen just goes back to the standard login form (with all the header/footer links again). 

![screen shot 2017-12-02 at 11 03 21 pm](https://user-images.githubusercontent.com/1012467/33522222-0ec20fa4-d7b5-11e7-9b25-024056f42ae0.png)

I've listed both of these bugs in one issue since they likely have the same root cause (or are at least related). It appears as though the app token/redirect link etc is lost when a second page is loaded, whether it be the login page again (after a failed login), or the MFA screen.

**Comment by DaveWoodCom** [comment]
Note, reproduced the issues above using enuts on macOS, but with a slight difference. The screens on enuts aways have the header/footer links. So perhaps they're being stripped by Apero?

**Comment by 33mhz** [comment]
A simple login page without the links is an option for developers.

I know it doesn't handle a failed MFA login. And cookies may be related... I don't know why it would do this if the MFA code is correct, though. I'm rewriting all of this handling now, though.
