### ISSUE TITLE
Verification email issues

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#49]
When signing up for a new account (paid or with an invite code), an initial email to verify the email address is not sent. The user needs to go to this page: https://pnut.io/account/discovery_and_identity and request a 're-send'.

After requesting the re-send, this alert is displayed:

    "A verification E-mail has been re-sent to the new address. Until it is verified, the old address will continue to be used."

Technically it's not a new address, it's using the existing address. Granted, it's a bit of a nitpick, but the issue continues. Two emails will be sent to the email address. One with a link to verify the email address and the text "Someone has requested that your pnut.io E-mail address be changed". No one requested a change. Only a verification of the same email. The second email sent is worse and includes the text: "Someone has requested that your pnut.io E-mail address be changed from sample@example.com to sample@example.com. If this has been in error, please contact support@pnut.io immediately, or change your E-mail address back, if you can." The whole message is pointless since it's the same email address.

**Comment by 33mhz** [comment]
Fixed the underlying issue.
