### ISSUE TITLE
Endpoint for client events (App Streams)

### ISSUE THREAD

**Issue by shawnthroop** [pnut-api/api-spec#5]
App.net provides an endpoint that makes sending push notifications possible, it is called [App Streams](https://developers.app.net/reference/resources/app-stream/). It is an endpoint that a client (in my case a server) can monitor and pass on parsed notifications (mentions, PMs, follow/unfollow etc) to APNS or another push notification platform.

I would love to see a similar endpoint for pnut.io so I could provide users with realtime notifications on their devices.

**Comment by blumenkraft** [comment]
+1

**Comment by 33mhz** [comment]
Handled on the next update.

**Comment by 33mhz** [comment]
Existing! Documentation isn't complete. Needs a how-to.
