### ISSUE TITLE
Requesting a data backup fails

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#55]
I just used the web site at https://pnut.io/account/data to request a backup of my data. It said it completed successfully and would email me the link.

The email arrived saying "Pnut.io Data Export for @5". @5 is not my username. Nor my user id. No idea what that's referring to. Perhaps it's sending me someone else's data? I can't tell because the link in the email doesn't work. It gives an access denied error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>655802EF84199325</RequestId>
<HostId>
4PYPl9INl6erzL5MO93wJ4HOyyxBuM5dNhXiwB/EleHBWn+53GtFB1VYladhP5DhaDBb6tKbDO8=
</HostId>
</Error>
```

**Comment by 33mhz** [comment]
Apologies - this was simply not including an empty folder in the last update. The @5 reference was the first character of your user id; it was very confused.

[edit]
I'll reset your account to be able to request another in a moment.

**Comment by DaveWoodCom** [comment]
Thanks. Confirmed fixed.
