### ISSUE TITLE
Pagination clarification

### ISSUE THREAD

**Issue by shawnthroop** [pnut-api/api-spec#6]
App.net paginates streams by providing a `max_id` and `min_id` in the response metadata of a request. Developers can then use these values to request more objects in the stream. This is great for fetching from the beginning and ends of streams because one can save the values in the model layer. However, things got tricky when you want to load from the middle of a stream where the `min/max_id` isn't know (I do this when I trim a stream and when I load missing data in gaps).

In these scenarios one can use a paginated object's `pagination_id` value. For user/post streams these are often the exact same as the `id` value. This is redundant but provides a consistent API for loading paginated streams regardless of what kind of objects were in the stream. 

I understand this is kind of a non-issue at the moment because non-user/post streams are still under construction and I can easily just use the `id` value like a gentleman. However, when non user/post streams are finished I would love to have a consistent "`pagination_id`" value across all streams that can be paginated. If this conflicts with the backend structure, a simple notation in the docs about which values can be used as `before/since_id` values would also suffice.

**Comment by 33mhz** [comment]
All paginated streams should have proper `pagination_id`s now. https://pnut.io/updates#2016-11-24.a

**Comment by shawnthroop** [comment]
You've been busy. Hats off to you
