### ISSUE TITLE
A Poll's options.is_your_response type doesn't match documentation

### ISSUE THREAD

**Issue by shawnthroop** [pnut-api/api-spec#60]
I've been experimenting with the polls endpoint today. When fetching/creating a poll, the objects in the `options` array do not match what is written in the Docs.

For `is_your_response` the Docs state:
> "`boolean` Optional. Present if authenticated as a user. True if user responded to the poll with this option."

An example snippet from a response:

```json
"options": [
	{
	    "text": "Yes",
	    "postion": 0,
	    "position": 1,
	    "is_your_response": 0,
	    "respondents": 0,
	    "respondent_ids": []
	},
	{
	    "text": "No",
	    "postion": 1,
	    "position": 2,
	    "is_your_response": 0,
	    "respondents": 0,
	    "respondent_ids": []
	}
],
...
```

Also worth noting, the `postion` key that is duplicated/misspelled. I just noticed it as I copied and pasted.

**Comment by 33mhz** [comment]
How does `is_your_response` not match the docs? Because it's `0` and `1` instead of `true`?

What poll ID gives these results? I don't see a poll with a `postion` key.

**Comment by shawnthroop** [comment]
Sorry, that was silly of me to not state specifically. Yes, `0` and `1` vs `true` and `false`. I understand the difference is minor but Swift likes to be precise.

I stupidly started testing different endpoints and deleted both of the polls that had this `postion` abnormality. Their `id`s where `123` and `124`.

I think the problem with the typo was on my end. I encoded the value as:
```json
{
    "text": "Yes",
    "postion": 0
}
```

The api seems to have kept my extra key and added the correct one like it should do. Sorry for the assumption of blame, it was my bad.

**Comment by shawnthroop** [comment]
Sorry, I double checked and the `postion` stuff was on my end.

**Comment by 33mhz** [comment]
Na, I'm not concerned. :+1: 

You're right, `is_your_response` _is_ supposed to boolean, not integers. And `position` is supposed to be string.

**Comment by shawnthroop** [comment]
Haha I didn’t even realize position should be a string. Though, I’m super happy with it as an integer; less custom decoding on my end.

**Comment by 33mhz** [comment]
`is_your_response` will be responding with boolean true/false in the future. I'm going to give developers some time to update their clients before I change it.
