### ISSUE TITLE
Invalid data returned when setting include_user=0 on File endpoints

### ISSUE THREAD

**Issue by shawnthroop** [pnut-api/api-spec#62]
Normally, when setting `include_user=0` for a request, a User `id` value is returned in the place of a User object. When accessing the File endpoints an empty string is returned.

This is a trimmed version of the response from `https://api.pnut.io/v0/files/4301?include_user=0`:

```json
{
  "meta": {
    "code": 200
  },
  "data": {
    "id": "4301",
    "user": ""
  }
}
```

I confirmed the same response for `/file/{file_id}` and `/users/me/files`.

**Comment by 33mhz** [comment]
Correct! Fixed. Thanks.
